import type { ComponentProps } from 'react';
import type MaterialIcons from 'react-native-vector-icons/MaterialIcons';

type IconName = ComponentProps<typeof MaterialIcons>['name'];

const THEME_ICON_MAP: Record<string, IconName> = {
  간구: 'pan-tool',
  감사: 'favorite-border',
  거룩함: 'emoji-events',
  격려: 'thumb-up',
  결단: 'check-circle',
  경배: 'church',
  계획: 'assignment',
  고난: 'terrain',
  고백: 'chat-bubble-outline',
  교회: 'church',
  골방: 'meeting-room',
  교제: 'groups',
  구속: 'shield',
  구원: 'card-giftcard',
  긍휼: 'volunteer-activism',
  기쁨: 'sentiment-satisfied-alt',
  기적: 'star',
  기도: 'pan-tool',
  나아감: 'arrow-upward',
  내어맡김: 'back-hand',
  닮음: 'account-circle',
  동행: 'directions-walk',
  말씀: 'menu-book',
  믿음: 'verified',
  보혈: 'umbrella',
  보호: 'security',
  복음: 'menu-book',
  봉헌: 'eco',
  부활: 'wb-sunny',
  부흥: 'local-fire-department',
  변화: 'sync',
  사랑: 'favorite',
  사명: 'flag',
  선교: 'public',
  성화: 'spa',
  선포: 'campaign',
  선하심: 'thumb-up',
  성령: 'air',
  성탄: 'card-giftcard',
  소망: 'lightbulb',
  순결: 'auto-awesome',
  순종: 'check',
  십자가: 'add',
  신뢰: 'handshake',
  신앙: 'verified',
  신분: 'badge',
  신실함: 'loyalty',
  승리: 'emoji-events',
  섬김: 'volunteer-activism',
  예배: 'church',
  예수님: 'person',
  영광: 'brightness-high',
  연단: 'fitness-center',
  연합: 'link',
  온전함: 'all-inclusive',
  용서: 'healing',
  위로: 'favorite-border',
  의지: 'anchor',
  은혜: 'favorite',
  인내: 'hourglass-empty',
  인도: 'explore',
  임재: 'visibility',
  전능하심: 'bolt',
  전도: 'record-voice-over',
  재림: 'cloud',
  정결: 'auto-awesome',
  중보: 'people',
  친밀함: 'favorite',
  창조: 'brightness-5',
  찬양: 'music-note',
  천국: 'cloud',
  충만: 'water-drop',
  축복: 'card-giftcard',
  탄생: 'child-care',
  통치: 'gavel',
  평안: 'spa',
  하나님: 'brightness-high',
  하나님나라: 'public',
  함께하심: 'groups',
  헌신: 'favorite',
  회개: 'refresh',
  회복: 'healing',
  희생: 'favorite-border',
};

export function getWorshipThemeIcon(theme: string): IconName {
  return THEME_ICON_MAP[theme] ?? 'label';
}
