export const boardColors = {
  bg: '#ffffff',
  card: '#ffffff',
  border: '#e8ecf0',
  borderLight: '#e2e8f0',
  text: '#111111',
  textSecondary: '#334155',
  textMuted: '#64748b',
  textMuted2: '#94a3b8',
  primary: '#2B7FFF',
  searchBg: '#ffffff',
  badgeInfoBg: '#E8F2FF',
  badgeInfoText: '#2B7FFF',
  badgeDailyBg: '#F0EFFC',
  badgeDailyText: '#7C6FE3',
  badgeCounselBg: '#FDF0E6',
  badgeCounselText: '#E27E36',
  badgeMissionBg: '#E6FBF0',
  badgeMissionText: '#22C55E',
  badgeNoticeBg: '#E8F2FF',
  badgeNoticeText: '#1e40af',
  noticeCardBg: '#f0f4ff',
  noticeCardBorder: '#1e40af',
  newBadge: '#FF3B30',
};
