export const homeColors = {
  bg: '#f0f3f7',
  card: '#ffffff',
  border: '#e8ecf0',
  text: '#111111',
  textMuted: '#8B95A1',
  textMuted2: '#9EA7B0',
  primary: '#2B7FFF',
  primaryLight: '#55AAFF',
  badgeBlueBg: '#E8F2FF',
  badgeRedBg: '#FFF0F0',
  badgeOrangeBg: '#FFF4EE',
  badgeRed: '#E53935',
  badgeOrange: '#F57C00',
  tabTrack: '#e8ecf0',
  alertGradientStart: '#EBF3FF',
  alertGradientEnd: '#DFF0FF',
  arrow: '#c9cdd2',
};
